<?php

namespace Database\Seeders;

use App\Models\Dishub;
use Illuminate\Database\Seeder;

class DishubSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'nama' => 'Dishub Provinsi DKI Jakarta',
                'singkatan' => 'DISHUB DKI',
                'provinsi' => 'DKI Jakarta',
                'kota' => 'Jakarta Pusat',
                'kecamatan' => 'Gambir',
                'kepala_dinas_nama' => 'Syafrin Liputo, A.T.D., M.T.',
                'kepala_dinas_nip' => '197105101997031005',
                'direktur_nama' => 'H. Ahmad Syarif, M.Si',
                'direktur_nip' => '198001012005011001',
            ],
            [
                'nama' => 'Dishub Kota Yogyakarta',
                'singkatan' => 'DISHUB JOG',
                'provinsi' => 'DI Yogyakarta',
                'kota' => 'Yogyakarta',
                'kecamatan' => 'Umbulharjo',
                'kepala_dinas_nama' => 'Agus Arif Nugroho, S.S.T.P.',
                'kepala_dinas_nip' => '197508151994121001',
                'direktur_nama' => 'Bambang Heru, M.T.',
                'direktur_nip' => '198501012008011002',
            ],
            [
                'nama' => 'Dishub Kota Surabaya',
                'singkatan' => 'DISHUB SBY',
                'provinsi' => 'Jawa Timur',
                'kota' => 'Surabaya',
                'kecamatan' => 'Gayungan',
                'kepala_dinas_nama' => 'Tundjung Iswandaru, S.T., M.M.',
                'kepala_dinas_nip' => '197204121998031004',
                'direktur_nama' => 'Ir. Hendro Cahyono',
                'direktur_nip' => '197805152003121001',
            ],
            [
                'nama' => 'Dishub Kota Bandung',
                'singkatan' => 'DISHUB BDG',
                'provinsi' => 'Jawa Barat',
                'kota' => 'Bandung',
                'kecamatan' => 'Gedebage',
                'kepala_dinas_nama' => 'Dadang Darmawan, S.Sos., M.Si.',
                'kepala_dinas_nip' => '196803101989031007',
                'direktur_nama' => 'Asep Kurnia, M.Pd.',
                'direktur_nip' => '197509202000031003',
            ],
            [
                'nama' => 'Dishub Kota Semarang',
                'singkatan' => 'DISHUB SMG',
                'provinsi' => 'Jawa Tengah',
                'kota' => 'Semarang',
                'kecamatan' => 'Semarang Barat',
                'kepala_dinas_nama' => 'Endro P. Martanto, S.T., M.M.',
                'kepala_dinas_nip' => '197012011996031002',
                'direktur_nama' => 'Dwi Santoso, S.T.',
                'direktur_nip' => '198211052009021001',
            ],
            [
                'nama' => 'Dishub Kota Medan',
                'singkatan' => 'DISHUB MDN',
                'provinsi' => 'Sumatera Utara',
                'kota' => 'Medan',
                'kecamatan' => 'Medan Kota',
                'kepala_dinas_nama' => 'Iswar Lubis, S.Si.T., M.T.',
                'kepala_dinas_nip' => '197406181997031003',
                'direktur_nama' => 'Rizky Hamdani, M.Si',
                'direktur_nip' => '198302142006041002',
            ],
            [
                'nama' => 'Dishub Kota Makassar',
                'singkatan' => 'DISHUB MKS',
                'provinsi' => 'Sulawesi Selatan',
                'kota' => 'Makassar',
                'kecamatan' => 'Tamalate',
                'kepala_dinas_nama' => 'Zainal Ibrahim, S.T.P., M.Si.',
                'kepala_dinas_nip' => '197601051996031001',
                'direktur_nama' => 'Andi Muhammad, M.T.',
                'direktur_nip' => '197908122005011004',
            ],
            [
                'nama' => 'Dishub Kota Palembang',
                'singkatan' => 'DISHUB PLM',
                'provinsi' => 'Sumatera Selatan',
                'kota' => 'Palembang',
                'kecamatan' => 'Ilir Timur I',
                'kepala_dinas_nama' => 'Afrizal Hasyim, S.Sos., M.M.',
                'kepala_dinas_nip' => '197104251992031005',
                'direktur_nama' => 'Faisal Reza, S.E.',
                'direktur_nip' => '198103102007011003',
            ],
            [
                'nama' => 'Dishub Kota Denpasar',
                'singkatan' => 'DISHUB DPS',
                'provinsi' => 'Bali',
                'kota' => 'Denpasar',
                'kecamatan' => 'Denpasar Utara',
                'kepala_dinas_nama' => 'I Ketut Sriawan, S.E.',
                'kepala_dinas_nip' => '196912311992031015',
                'direktur_nama' => 'Wayan Gede, M.Si',
                'direktur_nip' => '198412252010011001',
            ],
            [
                'nama' => 'Dishub Kota Balikpapan',
                'singkatan' => 'DISHUB BPN',
                'provinsi' => 'Kalimantan Timur',
                'kota' => 'Balikpapan',
                'kecamatan' => 'Balikpapan Kota',
                'kepala_dinas_nama' => 'Adwar Skenda Putra, S.Sos.',
                'kepala_dinas_nip' => '197310121994031003',
                'direktur_nama' => 'H. Rudy Syarif, M.T.',
                'direktur_nip' => '197706152002121002',
            ],
            [
                'nama' => 'Dishub Kota Malang',
                'singkatan' => 'DISHUB MLG',
                'provinsi' => 'Jawa Timur',
                'kota' => 'Malang',
                'kecamatan' => 'Klojen',
                'kepala_dinas_nama' => 'R. Saleh Putra, S.T., M.M.',
                'kepala_dinas_nip' => '197411201998031002',
                'direktur_nama' => 'Eko Wahyudi, S.Si.T.',
                'direktur_nip' => '198105052006041005',
            ],
            [
                'nama' => 'Dishub Kota Tangerang',
                'singkatan' => 'DISHUB TNG',
                'provinsi' => 'Banten',
                'kota' => 'Tangerang',
                'kecamatan' => 'Tangerang',
                'kepala_dinas_nama' => 'Achmad Suhaely, S.S.T.P., M.Si.',
                'kepala_dinas_nip' => '198108152000121001',
                'direktur_nama' => 'Donny Aris, M.Si',
                'direktur_nip' => '198207122005011003',
            ],
            [
                'nama' => 'Dishub Kota Bekasi',
                'singkatan' => 'DISHUB BKS',
                'provinsi' => 'Jawa Barat',
                'kota' => 'Bekasi',
                'kecamatan' => 'Bekasi Timur',
                'kepala_dinas_nama' => 'Zeno Bachtiar, S.T., M.Si.',
                'kepala_dinas_nip' => '197610102001121002',
                'direktur_nama' => 'Surya Kencana, S.T.',
                'direktur_nip' => '197903152003121004',
            ],
            [
                'nama' => 'Dishub Kota Banjarmasin',
                'singkatan' => 'DISHUB BJM',
                'provinsi' => 'Kalimantan Selatan',
                'kota' => 'Banjarmasin',
                'kecamatan' => 'Banjarmasin Tengah',
                'kepala_dinas_nama' => 'Slamet Begjo, S.H.',
                'kepala_dinas_nip' => '196705121990031008',
                'direktur_nama' => 'H. Muhammad Noor, M.Si',
                'direktur_nip' => '197811202002121001',
            ],
            [
                'nama' => 'Dishub Kota Pontianak',
                'singkatan' => 'DISHUB PTK',
                'provinsi' => 'Kalimantan Barat',
                'kota' => 'Pontianak',
                'kecamatan' => 'Pontianak Kota',
                'kepala_dinas_nama' => 'Yuli Trisna Ibrahim, S.T.',
                'kepala_dinas_nip' => '197707202001121003',
                'direktur_nama' => 'Zulkifli, M.T.',
                'direktur_nip' => '198004102005011002',
            ],
            [
                'nama' => 'Dishub Kota Bandar Lampung',
                'singkatan' => 'DISHUB BDL',
                'provinsi' => 'Lampung',
                'kota' => 'Bandar Lampung',
                'kecamatan' => 'Teluk Betung Utara',
                'kepala_dinas_nama' => 'Socia M. Ariansyah, S.T.P.',
                'kepala_dinas_nip' => '197805142000121001',
                'direktur_nama' => 'Agus Salim, M.Si',
                'direktur_nip' => '198206202006041003',
            ],
            [
                'nama' => 'Dishub Kota Padang',
                'singkatan' => 'DISHUB PDG',
                'provinsi' => 'Sumatera Barat',
                'kota' => 'Padang',
                'kecamatan' => 'Padang Timur',
                'kepala_dinas_nama' => 'Ances Kurniawan, S.S.T.P., M.Si.',
                'kepala_dinas_nip' => '198005122000031001',
                'direktur_nama' => 'Hendri Faisal, M.T.',
                'direktur_nip' => '198109152005011002',
            ],
            [
                'nama' => 'Dishub Kota Manado',
                'singkatan' => 'DISHUB MND',
                'provinsi' => 'Sulawesi Utara',
                'kota' => 'Manado',
                'kecamatan' => 'Wenang',
                'kepala_dinas_nama' => 'Jeffry Worang, S.E.',
                'kepala_dinas_nip' => '197003141996031004',
                'direktur_nama' => 'Lucky Senduk, M.Si',
                'direktur_nip' => '197802102003121001',
            ],
            [
                'nama' => 'Dishub Kota Pekanbaru',
                'singkatan' => 'DISHUB PKU',
                'provinsi' => 'Riau',
                'kota' => 'Pekanbaru',
                'kecamatan' => 'Sukajadi',
                'kepala_dinas_nama' => 'Yuliarso, S.S.T.P., M.Si.',
                'kepala_dinas_nip' => '197905152000121001',
                'direktur_nama' => 'Anton Siswanto, S.T.',
                'direktur_nip' => '198104122006041002',
            ],
            [
                'nama' => 'Dishub Kota Samarinda',
                'singkatan' => 'DISHUB SMD',
                'provinsi' => 'Kalimantan Timur',
                'kota' => 'Samarinda',
                'kecamatan' => 'Samarinda Ulu',
                'kepala_dinas_nama' => 'Hotmarulitua Manalu, S.Si.T., M.Sc.',
                'kepala_dinas_nip' => '198203142001121001',
                'direktur_nama' => 'Budi Utomo, M.T.',
                'direktur_nip' => '198305202008011003',
            ],
        ];

        foreach ($data as $d) {
            Dishub::create($d);
        }
    }
}