<?php

namespace Database\Seeders;

use App\Models\Dishub;
use Illuminate\Database\Seeder;

class DishubSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            // ================= DKI JAKARTA =================
            [
                'nama' => 'UP PKB Pulogadung',
                'singkatan' => 'PKB PLG',
                'provinsi' => 'DKI Jakarta',
                'kota' => 'Jakarta Timur',
                'kecamatan' => 'Pulogadung',
                'kepala_dinas_nama' => 'Drs. Syafrin Liputo, A.T.D., M.T.',
                'kepala_dinas_nip' => '197105101997031005',
                'direktur_nama' => 'H. Ahmad Syarif, M.Si',
                'direktur_nip' => '198001012005011001',
            ],
            [
                'nama' => 'UP PKB Ujung Menteng',
                'singkatan' => 'PKB UJM',
                'provinsi' => 'DKI Jakarta',
                'kota' => 'Jakarta Timur',
                'kecamatan' => 'Cakung',
                'kepala_dinas_nama' => 'Drs. Syafrin Liputo, A.T.D., M.T.',
                'kepala_dinas_nip' => '197105101997031005',
                'direktur_nama' => 'Budi Laksono, A.Md. LLAJ',
                'direktur_nip' => '198211052006041001',
            ],
            [
                'nama' => 'UP PKB Jagakarsa',
                'singkatan' => 'PKB JGK',
                'provinsi' => 'DKI Jakarta',
                'kota' => 'Jakarta Selatan',
                'kecamatan' => 'Jagakarsa',
                'kepala_dinas_nama' => 'Drs. Syafrin Liputo, A.T.D., M.T.',
                'kepala_dinas_nip' => '197105101997031005',
                'direktur_nama' => 'Taufik Hidayat, S.Sos.',
                'direktur_nip' => '197801202003121004',
            ],
            [
                'nama' => 'UP PKB Cilincing',
                'singkatan' => 'PKB CLC',
                'provinsi' => 'DKI Jakarta',
                'kota' => 'Jakarta Utara',
                'kecamatan' => 'Cilincing',
                'kepala_dinas_nama' => 'Drs. Syafrin Liputo, A.T.D., M.T.',
                'kepala_dinas_nip' => '197105101997031005',
                'direktur_nama' => 'Ferry Gunawan, M.Si',
                'direktur_nip' => '198405122009021005',
            ],
            [
                'nama' => 'UP PKB Kedaung Angke',
                'singkatan' => 'PKB KDA',
                'provinsi' => 'DKI Jakarta',
                'kota' => 'Jakarta Barat',
                'kecamatan' => 'Cengkareng',
                'kepala_dinas_nama' => 'Drs. Syafrin Liputo, A.T.D., M.T.',
                'kepala_dinas_nip' => '197105101997031005',
                'direktur_nama' => 'Eko Prasetyo, S.T.',
                'direktur_nip' => '198109302007011002',
            ],

            // ================= JAWA BARAT =================
            [
                'nama' => 'UPT PKB Kota Bandung',
                'singkatan' => 'PKB BDG',
                'provinsi' => 'Jawa Barat',
                'kota' => 'Bandung',
                'kecamatan' => 'Gedebage',
                'kepala_dinas_nama' => 'Dadang Darmawan, S.Sos., M.Si.',
                'kepala_dinas_nip' => '196803101989031007',
                'direktur_nama' => 'Asep Kurnia, M.Pd.',
                'direktur_nip' => '197509202000031003',
            ],
            [
                'nama' => 'UPT PKB Kota Bekasi',
                'singkatan' => 'PKB BKS',
                'provinsi' => 'Jawa Barat',
                'kota' => 'Bekasi',
                'kecamatan' => 'Bekasi Timur',
                'kepala_dinas_nama' => 'Zeno Bachtiar, S.T., M.Si.',
                'kepala_dinas_nip' => '197610102001121002',
                'direktur_nama' => 'Surya Kencana, S.T.',
                'direktur_nip' => '197903152003121004',
            ],
            [
                'nama' => 'UPTD PKB Kab. Bekasi',
                'singkatan' => 'PKB KABBKS',
                'provinsi' => 'Jawa Barat',
                'kota' => 'Kabupaten Bekasi',
                'kecamatan' => 'Cikarang Utara',
                'kepala_dinas_nama' => 'H. Yana Suyatna, S.IP., M.Si.',
                'kepala_dinas_nip' => '196911121995031001',
                'direktur_nama' => 'M. Ridwan, S.Si.T.',
                'direktur_nip' => '198305142010011002',
            ],
            [
                'nama' => 'UPT PKB Kota Bogor',
                'singkatan' => 'PKB BGR',
                'provinsi' => 'Jawa Barat',
                'kota' => 'Bogor',
                'kecamatan' => 'Bogor Timur',
                'kepala_dinas_nama' => 'Marse Hendra Saputra, S.STP.',
                'kepala_dinas_nip' => '197802111999031004',
                'direktur_nama' => 'Iwan Setiawan, M.T.',
                'direktur_nip' => '198108172006041005',
            ],
            [
                'nama' => 'UPT PKB Kab. Bogor',
                'singkatan' => 'PKB KABBGR',
                'provinsi' => 'Jawa Barat',
                'kota' => 'Kabupaten Bogor',
                'kecamatan' => 'Cibinong',
                'kepala_dinas_nama' => 'Agus Ridho, S.H., M.H.',
                'kepala_dinas_nip' => '197304221998031006',
                'direktur_nama' => 'Hendra Gunawan, S.T.',
                'direktur_nip' => '198012102005011003',
            ],
            [
                'nama' => 'UPT PKB Kota Depok',
                'singkatan' => 'PKB DPK',
                'provinsi' => 'Jawa Barat',
                'kota' => 'Depok',
                'kecamatan' => 'Cilodong',
                'kepala_dinas_nama' => 'Zamrowi Hasan, S.Sos., M.Si.',
                'kepala_dinas_nip' => '197506181996031002',
                'direktur_nama' => 'Ari Wibowo, S.T.',
                'direktur_nip' => '198402282009021001',
            ],
            [
                'nama' => 'UPT PKB Kota Cirebon',
                'singkatan' => 'PKB CRB',
                'provinsi' => 'Jawa Barat',
                'kota' => 'Cirebon',
                'kecamatan' => 'Kesambi',
                'kepala_dinas_nama' => 'Andi Armawan, S.Sos.',
                'kepala_dinas_nip' => '197009151992031008',
                'direktur_nama' => 'Dedi Sudrajat, M.Si.',
                'direktur_nip' => '197905202003121002',
            ],
            [
                'nama' => 'UPT PKB Kota Sukabumi',
                'singkatan' => 'PKB SKB',
                'provinsi' => 'Jawa Barat',
                'kota' => 'Sukabumi',
                'kecamatan' => 'Baros',
                'kepala_dinas_nama' => 'Imran Wardhani, S.T., M.M.',
                'kepala_dinas_nip' => '197411252000031004',
                'direktur_nama' => 'Rahmat Hidayat, S.T.',
                'direktur_nip' => '198207112008011003',
            ],

            // ================= BANTEN =================
            [
                'nama' => 'UPT PKB Kota Tangerang',
                'singkatan' => 'PKB TNG',
                'provinsi' => 'Banten',
                'kota' => 'Tangerang',
                'kecamatan' => 'Batuceper',
                'kepala_dinas_nama' => 'Achmad Suhaely, S.S.T.P., M.Si.',
                'kepala_dinas_nip' => '198108152000121001',
                'direktur_nama' => 'Donny Aris, M.Si',
                'direktur_nip' => '198207122005011003',
            ],
            [
                'nama' => 'UPT PKB Tangerang Selatan',
                'singkatan' => 'PKB TANGSEL',
                'provinsi' => 'Banten',
                'kota' => 'Tangerang Selatan',
                'kecamatan' => 'Setu',
                'kepala_dinas_nama' => 'H. Ilham Fathoni, M.Si.',
                'kepala_dinas_nip' => '197209181996031001',
                'direktur_nama' => 'Randi Saputra, S.T.',
                'direktur_nip' => '198403212009021002',
            ],
            [
                'nama' => 'UPTD PKB Kab. Tangerang',
                'singkatan' => 'PKB KABTNG',
                'provinsi' => 'Banten',
                'kota' => 'Kabupaten Tangerang',
                'kecamatan' => 'Balaraja',
                'kepala_dinas_nama' => 'Drs. H. Makmun, M.M.',
                'kepala_dinas_nip' => '196811231994031005',
                'direktur_nama' => 'Sigit Purnomo, M.T.',
                'direktur_nip' => '197912152005011004',
            ],
            [
                'nama' => 'UPT PKB Kota Serang',
                'singkatan' => 'PKB SRG',
                'provinsi' => 'Banten',
                'kota' => 'Serang',
                'kecamatan' => 'Cipocok Jaya',
                'kepala_dinas_nama' => 'M. Ikbal, S.T., M.Si.',
                'kepala_dinas_nip' => '197503141998031007',
                'direktur_nama' => 'Tubagus Rijal, M.T.',
                'direktur_nip' => '198308252009021001',
            ],

            // ================= JAWA TENGAH =================
            [
                'nama' => 'UPTD PKB Kota Semarang',
                'singkatan' => 'PKB SMG',
                'provinsi' => 'Jawa Tengah',
                'kota' => 'Semarang',
                'kecamatan' => 'Semarang Barat',
                'kepala_dinas_nama' => 'Endro P. Martanto, S.T., M.M.',
                'kepala_dinas_nip' => '197012011996031002',
                'direktur_nama' => 'Dwi Santoso, S.T.',
                'direktur_nip' => '198211052009021001',
            ],
            [
                'nama' => 'UPT PKB Kota Surakarta',
                'singkatan' => 'PKB SKT',
                'provinsi' => 'Jawa Tengah',
                'kota' => 'Surakarta',
                'kecamatan' => 'Jebres',
                'kepala_dinas_nama' => 'Taufiq Muhammad, S.Sos.',
                'kepala_dinas_nip' => '197405221995031004',
                'direktur_nama' => 'Heru Susanto, S.T.',
                'direktur_nip' => '198104182006041003',
            ],
            [
                'nama' => 'UPT PKB Kab. Banyumas',
                'singkatan' => 'PKB BMS',
                'provinsi' => 'Jawa Tengah',
                'kota' => 'Kabupaten Banyumas',
                'kecamatan' => 'Purwokerto Selatan',
                'kepala_dinas_nama' => 'Agus Nur Hadie, S.Sos., M.Si.',
                'kepala_dinas_nip' => '197210101994031005',
                'direktur_nama' => 'Pramono, A.Md. LLAJ',
                'direktur_nip' => '198009112003121002',
            ],
            [
                'nama' => 'UPT PKB Kota Tegal',
                'singkatan' => 'PKB TGL',
                'provinsi' => 'Jawa Tengah',
                'kota' => 'Tegal',
                'kecamatan' => 'Margadana',
                'kepala_dinas_nama' => 'Abdul Kadir, S.H.',
                'kepala_dinas_nip' => '196901251992031009',
                'direktur_nama' => 'Slamet Riyadi, S.T.',
                'direktur_nip' => '198402142010011004',
            ],
            [
                'nama' => 'UPT PKB Kab. Kudus',
                'singkatan' => 'PKB KDS',
                'provinsi' => 'Jawa Tengah',
                'kota' => 'Kabupaten Kudus',
                'kecamatan' => 'Jati',
                'kepala_dinas_nama' => 'Catur Sulistiyanto, S.Sos.',
                'kepala_dinas_nip' => '197311301998031001',
                'direktur_nama' => 'Budi Waluyo, S.T.',
                'direktur_nip' => '198207222008011006',
            ],

            // ================= DI YOGYAKARTA =================
            [
                'nama' => 'UPT PKB Kota Yogyakarta',
                'singkatan' => 'PKB JOG',
                'provinsi' => 'DI Yogyakarta',
                'kota' => 'Yogyakarta',
                'kecamatan' => 'Umbulharjo',
                'kepala_dinas_nama' => 'Agus Arif Nugroho, S.S.T.P.',
                'kepala_dinas_nip' => '197508151994121001',
                'direktur_nama' => 'Bambang Heru, M.T.',
                'direktur_nip' => '198501012008011002',
            ],
            [
                'nama' => 'UPT PKB Kab. Sleman',
                'singkatan' => 'PKB SLM',
                'provinsi' => 'DI Yogyakarta',
                'kota' => 'Kabupaten Sleman',
                'kecamatan' => 'Mlati',
                'kepala_dinas_nama' => 'Arip Pramana, S.IP., M.Si.',
                'kepala_dinas_nip' => '197107141996031004',
                'direktur_nama' => 'Eko Prasetyo, S.Si.T.',
                'direktur_nip' => '198311022006041001',
            ],
            [
                'nama' => 'UPT PKB Kab. Bantul',
                'singkatan' => 'PKB BTL',
                'provinsi' => 'DI Yogyakarta',
                'kota' => 'Kabupaten Bantul',
                'kecamatan' => 'Sewon',
                'kepala_dinas_nama' => 'Singgih Riyadi, S.E., M.M.',
                'kepala_dinas_nip' => '197402181999031005',
                'direktur_nama' => 'Yulianto, S.T.',
                'direktur_nip' => '198006152005011003',
            ],

            // ================= JAWA TIMUR =================
            [
                'nama' => 'UPTD PKB Tandes',
                'singkatan' => 'PKB TND',
                'provinsi' => 'Jawa Timur',
                'kota' => 'Surabaya',
                'kecamatan' => 'Tandes',
                'kepala_dinas_nama' => 'Tundjung Iswandaru, S.T., M.M.',
                'kepala_dinas_nip' => '197204121998031004',
                'direktur_nama' => 'Arif Rachman, M.T.',
                'direktur_nip' => '198302182008011003',
            ],
            [
                'nama' => 'UPTD PKB Wiyung',
                'singkatan' => 'PKB WYG',
                'provinsi' => 'Jawa Timur',
                'kota' => 'Surabaya',
                'kecamatan' => 'Wiyung',
                'kepala_dinas_nama' => 'Tundjung Iswandaru, S.T., M.M.',
                'kepala_dinas_nip' => '197204121998031004',
                'direktur_nama' => 'Bagas Prakoso, S.Si.T.',
                'direktur_nip' => '198506112010011005',
            ],
            [
                'nama' => 'UPT PKB Kab. Sidoarjo',
                'singkatan' => 'PKB SDA',
                'provinsi' => 'Jawa Timur',
                'kota' => 'Kabupaten Sidoarjo',
                'kecamatan' => 'Sidoarjo',
                'kepala_dinas_nama' => 'Benny Airlangga, S.H., M.H.',
                'kepala_dinas_nip' => '197605222000031002',
                'direktur_nama' => 'Agus Purnomo, S.T.',
                'direktur_nip' => '198109142007011004',
            ],
            [
                'nama' => 'UPT PKB Kab. Gresik',
                'singkatan' => 'PKB GSK',
                'provinsi' => 'Jawa Timur',
                'kota' => 'Kabupaten Gresik',
                'kecamatan' => 'Bunder',
                'kepala_dinas_nama' => 'Khusaini, S.E., M.Si.',
                'kepala_dinas_nip' => '197308111995031007',
                'direktur_nama' => 'Fahrudin, S.T.',
                'direktur_nip' => '198401202009021002',
            ],
            [
                'nama' => 'UPT PKB Kota Malang',
                'singkatan' => 'PKB MLG',
                'provinsi' => 'Jawa Timur',
                'kota' => 'Malang',
                'kecamatan' => 'Kedungkandang',
                'kepala_dinas_nama' => 'R. Saleh Putra, S.T., M.M.',
                'kepala_dinas_nip' => '197411201998031002',
                'direktur_nama' => 'Eko Wahyudi, S.Si.T.',
                'direktur_nip' => '198105052006041005',
            ],
            [
                'nama' => 'UPT PKB Kota Kediri',
                'singkatan' => 'PKB KDR',
                'provinsi' => 'Jawa Timur',
                'kota' => 'Kediri',
                'kecamatan' => 'Pesantren',
                'kepala_dinas_nama' => 'Didik Catur, S.T., M.Si.',
                'kepala_dinas_nip' => '197102141997031003',
                'direktur_nama' => 'Haryanto, M.T.',
                'direktur_nip' => '198011252005011006',
            ],
            [
                'nama' => 'UPT PKB Kab. Banyuwangi',
                'singkatan' => 'PKB BWX',
                'provinsi' => 'Jawa Timur',
                'kota' => 'Kabupaten Banyuwangi',
                'kecamatan' => 'Banyuwangi',
                'kepala_dinas_nama' => 'Pudjo Hartanto, S.Sos.',
                'kepala_dinas_nip' => '196906101991031005',
                'direktur_nama' => 'Andika Pratama, S.Si.T.',
                'direktur_nip' => '198503182010011003',
            ],

            // ================= SUMATERA =================
            [
                'nama' => 'UPT PKB Amplas',
                'singkatan' => 'PKB AMP',
                'provinsi' => 'Sumatera Utara',
                'kota' => 'Medan',
                'kecamatan' => 'Medan Amplas',
                'kepala_dinas_nama' => 'Iswar Lubis, S.Si.T., M.T.',
                'kepala_dinas_nip' => '197406181997031003',
                'direktur_nama' => 'Rizky Hamdani, M.Si',
                'direktur_nip' => '198302142006041002',
            ],
            [
                'nama' => 'UPT PKB Pinang Baris',
                'singkatan' => 'PKB PBR',
                'provinsi' => 'Sumatera Utara',
                'kota' => 'Medan',
                'kecamatan' => 'Medan Sunggal',
                'kepala_dinas_nama' => 'Iswar Lubis, S.Si.T., M.T.',
                'kepala_dinas_nip' => '197406181997031003',
                'direktur_nama' => 'Surya Nasution, S.T.',
                'direktur_nip' => '198107222008011004',
            ],
            [
                'nama' => 'UPT PKB Kota Palembang',
                'singkatan' => 'PKB PLM',
                'provinsi' => 'Sumatera Selatan',
                'kota' => 'Palembang',
                'kecamatan' => 'Ilir Barat I',
                'kepala_dinas_nama' => 'Afrizal Hasyim, S.Sos., M.M.',
                'kepala_dinas_nip' => '197104251992031005',
                'direktur_nama' => 'Faisal Reza, S.E.',
                'direktur_nip' => '198103102007011003',
            ],
            [
                'nama' => 'UPT PKB Kota Bandar Lampung',
                'singkatan' => 'PKB BDL',
                'provinsi' => 'Lampung',
                'kota' => 'Bandar Lampung',
                'kecamatan' => 'Rajabasa',
                'kepala_dinas_nama' => 'Socia M. Ariansyah, S.T.P.',
                'kepala_dinas_nip' => '197805142000121001',
                'direktur_nama' => 'Agus Salim, M.Si',
                'direktur_nip' => '198206202006041003',
            ],
            [
                'nama' => 'UPT PKB Kota Pekanbaru',
                'singkatan' => 'PKB PKU',
                'provinsi' => 'Riau',
                'kota' => 'Pekanbaru',
                'kecamatan' => 'Marpoyan Damai',
                'kepala_dinas_nama' => 'Yuliarso, S.S.T.P., M.Si.',
                'kepala_dinas_nip' => '197905152000121001',
                'direktur_nama' => 'Anton Siswanto, S.T.',
                'direktur_nip' => '198104122006041002',
            ],
            [
                'nama' => 'UPT PKB Kota Padang',
                'singkatan' => 'PKB PDG',
                'provinsi' => 'Sumatera Barat',
                'kota' => 'Padang',
                'kecamatan' => 'Koto Tangah',
                'kepala_dinas_nama' => 'Ances Kurniawan, S.S.T.P., M.Si.',
                'kepala_dinas_nip' => '198005122000031001',
                'direktur_nama' => 'Hendri Faisal, M.T.',
                'direktur_nip' => '198109152005011002',
            ],
            [
                'nama' => 'UPT PKB Kota Batam',
                'singkatan' => 'PKB BTM',
                'provinsi' => 'Kepulauan Riau',
                'kota' => 'Batam',
                'kecamatan' => 'Batam Kota',
                'kepala_dinas_nama' => 'Salim, S.Sos., M.Si.',
                'kepala_dinas_nip' => '197203181995031005',
                'direktur_nama' => 'Rizal Efendi, S.T.',
                'direktur_nip' => '198411222009021001',
            ],
            [
                'nama' => 'UPT PKB Kota Jambi',
                'singkatan' => 'PKB JMB',
                'provinsi' => 'Jambi',
                'kota' => 'Jambi',
                'kecamatan' => 'Kota Baru',
                'kepala_dinas_nama' => 'Saleh Ridho, S.STP.',
                'kepala_dinas_nip' => '198104112001121003',
                'direktur_nama' => 'Kurniawan, S.T.',
                'direktur_nip' => '198601152010011004',
            ],
            [
                'nama' => 'UPT PKB Kota Bengkulu',
                'singkatan' => 'PKB BGL',
                'provinsi' => 'Bengkulu',
                'kota' => 'Bengkulu',
                'kecamatan' => 'Gading Cempaka',
                'kepala_dinas_nama' => 'Hendri Kurniawan, S.E.',
                'kepala_dinas_nip' => '197608221999031002',
                'direktur_nama' => 'Budi Santoso, M.T.',
                'direktur_nip' => '198212102008011003',
            ],

            // ================= KALIMANTAN =================
            [
                'nama' => 'UPTD PKB Kota Balikpapan',
                'singkatan' => 'PKB BPN',
                'provinsi' => 'Kalimantan Timur',
                'kota' => 'Balikpapan',
                'kecamatan' => 'Balikpapan Selatan',
                'kepala_dinas_nama' => 'Adwar Skenda Putra, S.Sos.',
                'kepala_dinas_nip' => '197310121994031003',
                'direktur_nama' => 'H. Rudy Syarif, M.T.',
                'direktur_nip' => '197706152002121002',
            ],
            [
                'nama' => 'UPT PKB Kota Samarinda',
                'singkatan' => 'PKB SMD',
                'provinsi' => 'Kalimantan Timur',
                'kota' => 'Samarinda',
                'kecamatan' => 'Sungai Kunjang',
                'kepala_dinas_nama' => 'Hotmarulitua Manalu, S.Si.T., M.Sc.',
                'kepala_dinas_nip' => '198203142001121001',
                'direktur_nama' => 'Budi Utomo, M.T.',
                'direktur_nip' => '198305202008011003',
            ],
            [
                'nama' => 'UPT PKB Kota Banjarmasin',
                'singkatan' => 'PKB BJM',
                'provinsi' => 'Kalimantan Selatan',
                'kota' => 'Banjarmasin',
                'kecamatan' => 'Banjarmasin Selatan',
                'kepala_dinas_nama' => 'Slamet Begjo, S.H.',
                'kepala_dinas_nip' => '196705121990031008',
                'direktur_nama' => 'H. Muhammad Noor, M.Si',
                'direktur_nip' => '197811202002121001',
            ],
            [
                'nama' => 'UPT PKB Kota Pontianak',
                'singkatan' => 'PKB PTK',
                'provinsi' => 'Kalimantan Barat',
                'kota' => 'Pontianak',
                'kecamatan' => 'Pontianak Utara',
                'kepala_dinas_nama' => 'Yuli Trisna Ibrahim, S.T.',
                'kepala_dinas_nip' => '197707202001121003',
                'direktur_nama' => 'Zulkifli, M.T.',
                'direktur_nip' => '198004102005011002',
            ],
            [
                'nama' => 'UPT PKB Kota Palangka Raya',
                'singkatan' => 'PKB PLK',
                'provinsi' => 'Kalimantan Tengah',
                'kota' => 'Palangka Raya',
                'kecamatan' => 'Jekan Raya',
                'kepala_dinas_nama' => 'Alman P. Pakpahan, S.H., M.H.',
                'kepala_dinas_nip' => '197011151998031006',
                'direktur_nama' => 'Teguh Prasetyo, S.T.',
                'direktur_nip' => '198309142009021003',
            ],

            // ================= BALI & NUSA TENGGARA =================
            [
                'nama' => 'UPT PKB Kota Denpasar',
                'singkatan' => 'PKB DPS',
                'provinsi' => 'Bali',
                'kota' => 'Denpasar',
                'kecamatan' => 'Denpasar Barat',
                'kepala_dinas_nama' => 'I Ketut Sriawan, S.E.',
                'kepala_dinas_nip' => '196912311992031015',
                'direktur_nama' => 'Wayan Gede, M.Si',
                'direktur_nip' => '198412252010011001',
            ],
            [
                'nama' => 'UPT PKB Kab. Badung',
                'singkatan' => 'PKB BDG',
                'provinsi' => 'Bali',
                'kota' => 'Kabupaten Badung',
                'kecamatan' => 'Mengwi',
                'kepala_dinas_nama' => 'A.A. Ngurah Rai Yuda Dharma, S.Sos.',
                'kepala_dinas_nip' => '197103181993031008',
                'direktur_nama' => 'Made Suardana, S.T.',
                'direktur_nip' => '198205112007011002',
            ],
            [
                'nama' => 'UPT PKB Kota Mataram',
                'singkatan' => 'PKB MTR',
                'provinsi' => 'Nusa Tenggara Barat',
                'kota' => 'Mataram',
                'kecamatan' => 'Sandubaya',
                'kepala_dinas_nama' => 'M. Zulkarwin, S.STP.',
                'kepala_dinas_nip' => '197904222000121004',
                'direktur_nama' => 'Lalu Fathurrahman, M.T.',
                'direktur_nip' => '198510102010011005',
            ],
            [
                'nama' => 'UPT PKB Kota Kupang',
                'singkatan' => 'PKB KPG',
                'provinsi' => 'Nusa Tenggara Timur',
                'kota' => 'Kupang',
                'kecamatan' => 'Oebobo',
                'kepala_dinas_nama' => 'Bernadinus Mere, AP., M.Si.',
                'kepala_dinas_nip' => '197508141996031002',
                'direktur_nama' => 'Fransiskus Xaverius, S.T.',
                'direktur_nip' => '198111202008011003',
            ],

            // ================= SULAWESI & INDONESIA TIMUR =================
            [
                'nama' => 'UPT PKB Kota Makassar',
                'singkatan' => 'PKB MKS',
                'provinsi' => 'Sulawesi Selatan',
                'kota' => 'Makassar',
                'kecamatan' => 'Biringkanaya',
                'kepala_dinas_nama' => 'Zainal Ibrahim, S.T.P., M.Si.',
                'kepala_dinas_nip' => '197601051996031001',
                'direktur_nama' => 'Andi Muhammad, M.T.',
                'direktur_nip' => '197908122005011004',
            ],
            [
                'nama' => 'UPT PKB Kota Manado',
                'singkatan' => 'PKB MND',
                'provinsi' => 'Sulawesi Utara',
                'kota' => 'Manado',
                'kecamatan' => 'Mapanget',
                'kepala_dinas_nama' => 'Jeffry Worang, S.E.',
                'kepala_dinas_nip' => '197003141996031004',
                'direktur_nama' => 'Lucky Senduk, M.Si',
                'direktur_nip' => '197802102003121001',
            ],
            [
                'nama' => 'UPT PKB Kota Kendari',
                'singkatan' => 'PKB KDI',
                'provinsi' => 'Sulawesi Tenggara',
                'kota' => 'Kendari',
                'kecamatan' => 'Puuwatu',
                'kepala_dinas_nama' => 'Laode Muh. Ali, S.Sos.',
                'kepala_dinas_nip' => '197211151995031006',
                'direktur_nama' => 'Hasrullah, S.T.',
                'direktur_nip' => '198406182009021002',
            ],
            [
                'nama' => 'UPT PKB Kota Ambon',
                'singkatan' => 'PKB AMB',
                'provinsi' => 'Maluku',
                'kota' => 'Ambon',
                'kecamatan' => 'Baguala',
                'kepala_dinas_nama' => 'Roby Sapulette, S.T., M.T.',
                'kepala_dinas_nip' => '197401201999031002',
                'direktur_nama' => 'Yohanes Patty, M.Si',
                'direktur_nip' => '198109112006041005',
            ],
            [
                'nama' => 'UPT PKB Kota Jayapura',
                'singkatan' => 'PKB JYP',
                'provinsi' => 'Papua',
                'kota' => 'Jayapura',
                'kecamatan' => 'Abepura',
                'kepala_dinas_nama' => 'Justin Sitorus, S.H., M.H.',
                'kepala_dinas_nip' => '196810251994031007',
                'direktur_nama' => 'Samuel Yarangga, S.T.',
                'direktur_nip' => '198005122005011003',
            ],
            [
                'nama' => 'UPT PKB Kota Sorong',
                'singkatan' => 'PKB SRG',
                'provinsi' => 'Papua Barat Daya',
                'kota' => 'Sorong',
                'kecamatan' => 'Sorong Timur',
                'kepala_dinas_nama' => 'Paul Yarisetouw, S.Sos.',
                'kepala_dinas_nip' => '197307141998031001',
                'direktur_nama' => 'Klemens Kambu, M.T.',
                'direktur_nip' => '198302242008011004',
            ],
        ];

        foreach ($data as $d) {
            Dishub::create($d);
        }
    }
}